/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as SirkulerRouteImport } from './routes/sirkuler'
import { Route as BilgilerIndexRouteImport } from './routes/bilgiler.index'
import { Route as BilgilerSlugRouteImport } from './routes/bilgiler.$slug'
import { Route as HizmetlerimizIndexRouteImport } from './routes/hizmetlerimiz.index'
import { Route as HizmetlerimizSlugRouteImport } from './routes/hizmetlerimiz.$slug'
import { Route as InsanKaynaklariIndexRouteImport } from './routes/insan-kaynaklari.index'
import { Route as InsanKaynaklariAcikPozisyonlarRouteImport } from './routes/insan-kaynaklari.acik-pozisyonlar'
import { Route as InsanKaynaklariIlanYonetimiRouteImport } from './routes/insan-kaynaklari.ilan-yonetimi'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalPanelRouteImport } from './routes/portal.panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SirkulerRoute = SirkulerRouteImport.update({
  id: '/sirkuler',
  path: '/sirkuler',
  getParentRoute: () => rootRouteImport,
} as any)
const BilgilerIndexRoute = BilgilerIndexRouteImport.update({
  id: '/bilgiler/',
  path: '/bilgiler/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilgilerSlugRoute = BilgilerSlugRouteImport.update({
  id: '/bilgiler/$slug',
  path: '/bilgiler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizIndexRoute = HizmetlerimizIndexRouteImport.update({
  id: '/hizmetlerimiz/',
  path: '/hizmetlerimiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizSlugRoute = HizmetlerimizSlugRouteImport.update({
  id: '/hizmetlerimiz/$slug',
  path: '/hizmetlerimiz/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsanKaynaklariIndexRoute = InsanKaynaklariIndexRouteImport.update({
  id: '/insan-kaynaklari/',
  path: '/insan-kaynaklari/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsanKaynaklariAcikPozisyonlarRoute =
  InsanKaynaklariAcikPozisyonlarRouteImport.update({
    id: '/insan-kaynaklari/acik-pozisyonlar',
    path: '/insan-kaynaklari/acik-pozisyonlar',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsanKaynaklariIlanYonetimiRoute =
  InsanKaynaklariIlanYonetimiRouteImport.update({
    id: '/insan-kaynaklari/ilan-yonetimi',
    path: '/insan-kaynaklari/ilan-yonetimi',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPanelRoute = PortalPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/portal': typeof PortalRouteWithChildren
  '/sirkuler': typeof SirkulerRoute
  '/bilgiler/$slug': typeof BilgilerSlugRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/insan-kaynaklari/acik-pozisyonlar': typeof InsanKaynaklariAcikPozisyonlarRoute
  '/insan-kaynaklari/ilan-yonetimi': typeof InsanKaynaklariIlanYonetimiRoute
  '/portal/panel': typeof PortalPanelRoute
  '/bilgiler/': typeof BilgilerIndexRoute
  '/hizmetlerimiz/': typeof HizmetlerimizIndexRoute
  '/insan-kaynaklari/': typeof InsanKaynaklariIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/sirkuler': typeof SirkulerRoute
  '/bilgiler/$slug': typeof BilgilerSlugRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/insan-kaynaklari/acik-pozisyonlar': typeof InsanKaynaklariAcikPozisyonlarRoute
  '/insan-kaynaklari/ilan-yonetimi': typeof InsanKaynaklariIlanYonetimiRoute
  '/portal/panel': typeof PortalPanelRoute
  '/bilgiler': typeof BilgilerIndexRoute
  '/hizmetlerimiz': typeof HizmetlerimizIndexRoute
  '/insan-kaynaklari': typeof InsanKaynaklariIndexRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/portal': typeof PortalRouteWithChildren
  '/sirkuler': typeof SirkulerRoute
  '/bilgiler/$slug': typeof BilgilerSlugRoute
  '/hizmetlerimiz/$slug': typeof HizmetlerimizSlugRoute
  '/insan-kaynaklari/acik-pozisyonlar': typeof InsanKaynaklariAcikPozisyonlarRoute
  '/insan-kaynaklari/ilan-yonetimi': typeof InsanKaynaklariIlanYonetimiRoute
  '/portal/panel': typeof PortalPanelRoute
  '/bilgiler/': typeof BilgilerIndexRoute
  '/hizmetlerimiz/': typeof HizmetlerimizIndexRoute
  '/insan-kaynaklari/': typeof InsanKaynaklariIndexRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hakkimizda'
    | '/iletisim'
    | '/portal'
    | '/sirkuler'
    | '/bilgiler/$slug'
    | '/hizmetlerimiz/$slug'
    | '/insan-kaynaklari/acik-pozisyonlar'
    | '/insan-kaynaklari/ilan-yonetimi'
    | '/portal/panel'
    | '/bilgiler/'
    | '/hizmetlerimiz/'
    | '/insan-kaynaklari/'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hakkimizda'
    | '/iletisim'
    | '/sirkuler'
    | '/bilgiler/$slug'
    | '/hizmetlerimiz/$slug'
    | '/insan-kaynaklari/acik-pozisyonlar'
    | '/insan-kaynaklari/ilan-yonetimi'
    | '/portal/panel'
    | '/bilgiler'
    | '/hizmetlerimiz'
    | '/insan-kaynaklari'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/hakkimizda'
    | '/iletisim'
    | '/portal'
    | '/sirkuler'
    | '/bilgiler/$slug'
    | '/hizmetlerimiz/$slug'
    | '/insan-kaynaklari/acik-pozisyonlar'
    | '/insan-kaynaklari/ilan-yonetimi'
    | '/portal/panel'
    | '/bilgiler/'
    | '/hizmetlerimiz/'
    | '/insan-kaynaklari/'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  PortalRoute: typeof PortalRouteWithChildren
  SirkulerRoute: typeof SirkulerRoute
  BilgilerSlugRoute: typeof BilgilerSlugRoute
  HizmetlerimizSlugRoute: typeof HizmetlerimizSlugRoute
  InsanKaynaklariAcikPozisyonlarRoute: typeof InsanKaynaklariAcikPozisyonlarRoute
  InsanKaynaklariIlanYonetimiRoute: typeof InsanKaynaklariIlanYonetimiRoute
  BilgilerIndexRoute: typeof BilgilerIndexRoute
  HizmetlerimizIndexRoute: typeof HizmetlerimizIndexRoute
  InsanKaynaklariIndexRoute: typeof InsanKaynaklariIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sirkuler': {
      id: '/sirkuler'
      path: '/sirkuler'
      fullPath: '/sirkuler'
      preLoaderRoute: typeof SirkulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilgiler/': {
      id: '/bilgiler/'
      path: '/bilgiler'
      fullPath: '/bilgiler/'
      preLoaderRoute: typeof BilgilerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilgiler/$slug': {
      id: '/bilgiler/$slug'
      path: '/bilgiler/$slug'
      fullPath: '/bilgiler/$slug'
      preLoaderRoute: typeof BilgilerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz/': {
      id: '/hizmetlerimiz/'
      path: '/hizmetlerimiz'
      fullPath: '/hizmetlerimiz/'
      preLoaderRoute: typeof HizmetlerimizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz/$slug': {
      id: '/hizmetlerimiz/$slug'
      path: '/hizmetlerimiz/$slug'
      fullPath: '/hizmetlerimiz/$slug'
      preLoaderRoute: typeof HizmetlerimizSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insan-kaynaklari/': {
      id: '/insan-kaynaklari/'
      path: '/insan-kaynaklari'
      fullPath: '/insan-kaynaklari/'
      preLoaderRoute: typeof InsanKaynaklariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insan-kaynaklari/acik-pozisyonlar': {
      id: '/insan-kaynaklari/acik-pozisyonlar'
      path: '/insan-kaynaklari/acik-pozisyonlar'
      fullPath: '/insan-kaynaklari/acik-pozisyonlar'
      preLoaderRoute: typeof InsanKaynaklariAcikPozisyonlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insan-kaynaklari/ilan-yonetimi': {
      id: '/insan-kaynaklari/ilan-yonetimi'
      path: '/insan-kaynaklari/ilan-yonetimi'
      fullPath: '/insan-kaynaklari/ilan-yonetimi'
      preLoaderRoute: typeof InsanKaynaklariIlanYonetimiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/panel': {
      id: '/portal/panel'
      path: '/panel'
      fullPath: '/portal/panel'
      preLoaderRoute: typeof PortalPanelRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalPanelRoute: typeof PortalPanelRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPanelRoute: PortalPanelRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  PortalRoute: PortalRouteWithChildren,
  SirkulerRoute: SirkulerRoute,
  BilgilerSlugRoute: BilgilerSlugRoute,
  HizmetlerimizSlugRoute: HizmetlerimizSlugRoute,
  InsanKaynaklariAcikPozisyonlarRoute: InsanKaynaklariAcikPozisyonlarRoute,
  InsanKaynaklariIlanYonetimiRoute: InsanKaynaklariIlanYonetimiRoute,
  BilgilerIndexRoute: BilgilerIndexRoute,
  HizmetlerimizIndexRoute: HizmetlerimizIndexRoute,
  InsanKaynaklariIndexRoute: InsanKaynaklariIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
